src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionRepository::class)]
class Mission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 50)]
    private ?string $pays = null;

    #[ORM\Column(length: 50)]
    private ?string $code = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $specialite_d = null;

    #[ORM\ManyToMany(targetEntity: Agent::class, inversedBy: 'missions')]
    private Collection $agents;

    #[ORM\ManyToMany(targetEntity: Contact::class, inversedBy: 'missions')]
    private Collection $contacts;

    #[ORM\ManyToMany(targetEntity: Cible::class, inversedBy: 'missions')]
    private Collection $cibles;

    #[ORM\ManyToMany(targetEntity: Planque::class, inversedBy: 'missions')]
    private Collection $planques;

    #[ORM\Column(length: 50)]
    private ?string $type = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    public function __construct()
    {
        $this->agents = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->cibles = new ArrayCollection();
        $this->planques = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getSpecialiteD(): ?string
    {
        return $this->specialite_d;
    }

    public function setSpecialiteD(?string $specialite_d): static
    {
        $this->specialite_d = $specialite_d;

        return $this;
    }

    /**
     * @return Collection<int, Agent>
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): static
    {
        if (!$this->agents->contains($agent)) {
            $this->agents->add($agent);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): static
    {
        $this->agents->removeElement($agent);

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): static
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts->add($contact);
        }

        return $this;
    }

    public function removeContact(Contact $contact): static
    {
        $this->contacts->removeElement($contact);

        return $this;
    }

    /**
     * @return Collection<int, Cible>
     */
    public function getCibles(): Collection
    {
        return $this->cibles;
    }

    public function addCible(Cible $cible): static
    {
        if (!$this->cibles->contains($cible)) {
            $this->cibles->add($cible);
        }

        return $this;
    }

    public function removeCible(Cible $cible): static
    {
        $this->cibles->removeElement($cible);

        return $this;
    }

    /**
     * @return Collection<int, Planque>
     */
    public function getPlanques(): Collection
    {
        return $this->planques;
    }

    public function addPlanque(Planque $planque): static
    {
        if (!$this->planques->contains($planque)) {
            $this->planques->add($planque);
        }

        return $this;
    }

    public function removePlanque(Planque $planque): static
    {
        $this->planques->removeElement($planque);

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }
}

src/Controller/MissionController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Repository\MissionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/mission')]
class MissionController extends AbstractController
{
    #[Route('/', name: 'app_mission', methods: ['GET'])]
    public function index(Request $request, PaginatorInterface $paginator, MissionRepository $missionRepository): Response
    {

        $queryBuilder = $missionRepository->createQueryBuilder('m');


        $query = $queryBuilder->getQuery();
        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10 // Nombre d'éléments par page
        );

        return $this->render('mission/index.html.twig', [
            'missions' => $pagination, // Utilise la pagination au lieu de findAll()
            'pagination' => $pagination,
        ]);
    }

    #[Route('/search', name: 'app_mission_search', methods: ['GET'])]
    public function search(Request $request, MissionRepository $missionRepository): Response
    {
        $searchTerm = $request->query->get('term');
    
        $queryBuilder = $missionRepository->createQueryBuilder('m');
    
        if ($searchTerm) {
            $queryBuilder
                ->select('m') // Sélectionne toutes les données de la mission
                ->andWhere('m.titre LIKE :term OR m.description LIKE :term OR m.pays LIKE :term OR m.code LIKE :term OR m.type LIKE :term OR m.statut LIKE :term OR m.id = :id')
                ->setParameter('term', '%' . $searchTerm . '%')
                ->setParameter('id', $searchTerm);
        }
    
        $missions = $queryBuilder->getQuery()->getResult(); // Récupère les résultats sous forme d'entités Mission
    
        // Transforme les résultats en tableau pour la réponse JSON
        $formattedMissions = [];
        foreach ($missions as $mission) {
            $formattedMissions[] = [
                'id' => $mission->getId(),
                'code' => $mission->getCode(),
                'titre' => $mission->getTitre(),
                'description' => $mission->getDescription(),
                'statut' => $mission->getStatut(),
                // Ajoute d'autres champs si nécessaire
            ];
        }
    
        // Retourne la réponse JSON
        return new JsonResponse($formattedMissions);
    }
    
    

    #[Route('/{id}', name: 'app_mission_show', methods: ['GET'])]
    public function show(Mission $mission): Response
    {
        return $this->render('mission/show.html.twig', [
            'mission' => $mission,
        ]);
    }
}

templates/mission/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Missions
{% endblock %}

{% block body %}
	<h1 class="mt-5">Liste des missions</h1>

	{% include "partials/pagination.html.twig" %}


	<table class="table">
		<thead>
			<tr class="table-dark">
				<th>Code</th>
				<th>Titre</th>
				<th>Description</th>
				<th>Pays</th>
				<th>Specialité requise</th>
				<th>Statut</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for mission in missions %}
				<tr class="table-secondary bn border-bottom border-2 border-dark">
					<td>{{ mission.code }}</td>
					<td>{{ mission.titre }}</td>
					<td>{{ mission.description }}</td>
					<td>{{ mission.pays }}</td>
					<td>{{ mission.specialiteD }}</td>
					<td>
						<span class="badge rounded-pill
								                                {% if mission.statut == 'En préparation' %}bg-info
								                                {% elseif mission.statut == 'En cours' %}bg-warning
								                                {% elseif mission.statut == 'Terminé' %}bg-success
								                                {% elseif mission.statut == 'Échec' %}bg-danger
								                                {% endif %}">
							{{ mission.statut }}
						</span>
					</td>
					<td>
						<a href="{{ path('app_mission_show', {'id': mission.id}) }}" class="btn btn-light">Détail</a>
					</td>
				</tr>

			{% else %}
				<tr>
					<td colspan="7">Pas de missions trouvées...</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>


	{% include "partials/pagination.html.twig" %}
{% endblock %}

templates/mission/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Mission
	{{ mission.id }}
{% endblock %}

{% block body %}
	<div class="container mt-4 ">
		<div class="card mt-5 border-info mb-3 bg-info bg-opacity-10">
            <div class="card-header border-info  mb-3">
                <h1 class="card-title mb-0 ">Mission : {{ mission.titre }}</h1>
            </div>
		<div class="card-body row ">
                <div class="col-md-6 ">
                    <table class="table ">
					<tbody>
						<tr>
							<th class ="bg-transparent">Date de début:</th>
							<td class ="bg-transparent">{{ mission.dateDebut ? mission.dateDebut|date('d-m-Y') : 'N/A' }}</td>
						</tr>

						<tr>
							<th class ="bg-transparent">Code:</th>
							<td class ="bg-transparent">{{ mission.code }}</td>
						</tr>
						<tr>
							<th class ="bg-transparent">Type:</th>
							<td class ="bg-transparent">{{ mission.type }}</td>
						</tr>
						<tr>
							<th class ="bg-transparent">Description:</th>
							<td class ="bg-transparent">{{ mission.description }}</td>
						</tr>
						<th class ="bg-transparent">Agent(s):</th>
						<td class ="bg-transparent">
							<ul class="list-unstyled">
								{% for agent in mission.agents %}
									<li>
										<strong>Code:</strong>
										{{ agent.code }}<br>
										<strong>Nom:</strong>
										{{ agent.nom }}
										{{ agent.prenom }}<br>
										<strong>Date de naissance:</strong>
										{{ agent.naissance|date('d-m-Y') }}<br>
										<strong>Pays:</strong>
										{{ agent.pays }}<br>
										<strong>Spécialité:</strong>
										{{ agent.specialite }}<br>
									</li>
								{% endfor %}
							</ul>
						</td>
					</tbody>
				</tr>
				<tr>
					<th class ="bg-transparent">Contact(s):</th>
					<td class ="bg-transparent">
						<ul class="list-unstyled">
							{% for contact in mission.contacts %}
								<li>
									<strong>Code:</strong>
									{{ contact.code }}<br>
									<strong>Nom:</strong>
									{{ contact.nom }}
									{{ contact.prenom }}<br>
									<strong>Date de naissance:</strong>
									{{ contact.naissance|date('d-m-Y') }}<br>
									<strong>Pays:</strong>
									{{ contact.pays }}<br>
								</li>
							{% endfor %}
						</ul>
					</td>
				</tr>


			</tbody>
		</table>
	</div>

	<!-- Colonne de droite -->
	<div class="col-md-6">
                    <table class="table">
			<tbody>
            
				<tr>
					<th class ="bg-transparent">Date de fin:</th>
					<td class ="bg-transparent">{{ mission.dateFin ? mission.dateFin|date('d-m-Y') : 'N/A' }}</td>
				</tr>
				<tr>
                <tr>
					<th class ="bg-transparent">Statut:</th>
					<td class ="bg-transparent">{{ mission.statut }}</td>
				</tr>
					<th class ="bg-transparent">Pays:</th>
					<td class ="bg-transparent">{{ mission.pays }}</td>
				</tr>
				<tr>
					<th class ="bg-transparent">Spécialité(s) requise(s):</th>
					<td class ="bg-transparent">{{ mission.specialiteD }}</td>
				</tr>
				<tr></tr>
				<tr>
					<th class ="bg-transparent">Cible(s):</th>
					<td class ="bg-transparent">
						<ul class="list-unstyled">
							{% for cible in mission.cibles %}
								<li>
									<strong>Code:</strong>
									{{ cible.code }}<br>
									<strong>Nom:</strong>
									{{ cible.nom }}
									{{ cible.prenom }}<br>
									<strong>Date de naissance:</strong>
									{{ cible.naissance|date('d-m-Y') }}<br>
									<strong>Pays:</strong>
									{{ cible.pays }}<br>
								</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
				<tr>
					<th class ="bg-transparent">Planque:</th>
					<td class ="bg-transparent">
						<ul class="list-unstyled">
							{% for planque in mission.planques %}
								<li>
									<strong>Code:</strong>
									{{ planque.code }}<br>
									<strong>Adresse:</strong>
									{{ planque.adresse }}<br>
									<strong>Pays:</strong>
									{{ planque.pays }}<br>
									<strong>Type:</strong>
									{{ planque.type }}<br>
								</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<a href="{{ path('app_mission') }}" class ="btn btn-info">Retour</a></div>{% endblock %}